# Generated by Django 4.1.3 on 2023-01-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_appreciate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appreciate',
            old_name='work',
            new_name='post',
        ),
    ]
